server:
  port: 8080
  servlet:
    context-path: /eleme
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/eleme?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    mode: HTML

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.etc.entity

